name: CI
on: [push]
jobs:
  tailwindcss-update:
    name: Generate Tailwind CSS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate Tailwind CSS
        uses: ZoeyVid/tailwindcss-update@v1.4.0
        with:
          input: assets/app-tailwind.css
          output: assets/app.css
          params: ''
      - name: Commit & Push
        run: |
          git add --force assets/app.css
          git config user.name "Steelmonks"
          git config user.email "164031344+Steelmonks-Admin@users.noreply.github.com"
          git diff-index --quiet HEAD || git commit -m "ci: tailwindcss-update"
          git push
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lighthouse
        uses: shopify/lighthouse-ci-action@v1
        with:
          access_token: ${{ secrets.SHOP_ACCESS_TOKEN }}
          store: ${{ secrets.SHOP_STORE }}
          password: ${{ secrets.SHOP_PASSWORD }}
          lhci_github_app_token: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          product_handle: ${{ secrets.SHOP_PRODUCT_HANDLE }}
          collection_handle: ${{ secrets.SHOP_COLLECTION_HANDLE }}
  theme-check:
    name: Theme Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Shopify CLI
        run: npm install -g @shopify/cli @shopify/theme
      - name: Create theme-check config
        run: |
          echo 'extends: []' > .theme-check.yml
          echo 'ignore:' >> .theme-check.yml
          echo '  - node_modules/**' >> .theme-check.yml
      - name: Run Theme Check
        run: npx @shopify/theme-check
