name: CI
on: [push]
jobs:
  tailwindcss-update:
    name: Generate Tailwind CSS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TAILWIND_GITHUB_TOKEN }}
          persist-credentials: true
          fetch-depth: 0
      - name: Fix Git Permissions
        run: |
          echo "Fixing Git permissions..."
          # Get the current user and group
          CURRENT_USER=$(whoami)
          CURRENT_GROUP=$(id -gn)
          echo "Current user: $CURRENT_USER"
          echo "Current group: $CURRENT_GROUP"

          # Set extremely permissive permissions for the entire workspace
          sudo chmod -R 777 .

          # Ensure .git directory has full permissions
          sudo chmod -R 777 .git
          sudo chmod -R 777 .git/objects

          # Set ownership to the current user
          sudo chown -R $CURRENT_USER:$CURRENT_GROUP .
          sudo chown -R $CURRENT_USER:$CURRENT_GROUP .git

          # Configure Git to trust the workspace
          git config --global --add safe.directory "$(pwd)"

          # Debug output
          echo "Workspace permissions:"
          ls -la
          echo "Git directory permissions:"
          ls -la .git
          echo "Git objects directory permissions:"
          ls -la .git/objects
          echo "Git config:"
          git config --list
      - name: Debug Git Configuration
        run: |
          echo "Git user configuration:"
          git config --list
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la
          echo "Git status:"
          git status
      - name: Generate Tailwind CSS
        uses: ZoeyVid/tailwindcss-update@v1.4.0
        with:
          input: assets/app-tailwind.css
          output: assets/app.css
          params: ''
      - name: Debug File Permissions
        run: |
          echo "File permissions after generation:"
          ls -la assets/
          echo "Git status after generation:"
          git status
      - name: Commit & Push
        run: |
          echo "Attempting to add file..."
          # Configure Git user
          git config user.name "Steelmonks"
          git config user.email "164031344+Steelmonks-Admin@users.noreply.github.com"

          # Ensure permissions are still correct before commit
          sudo chmod -R 777 .
          sudo chmod -R 777 .git

          # Add and commit changes
          git add --force assets/app.css
          echo "Git status after add:"
          git status
          git commit -m "ci: tailwindcss-update" || echo "No changes to commit"
          echo "Git status after commit:"
          git status
          echo "Attempting to push..."
          git push
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lighthouse
        uses: shopify/lighthouse-ci-action@v1
        with:
          access_token: ${{ secrets.SHOP_ACCESS_TOKEN }}
          store: ${{ secrets.SHOP_STORE }}
          password: ${{ secrets.SHOP_PASSWORD }}
          lhci_github_app_token: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          product_handle: ${{ secrets.SHOP_PRODUCT_HANDLE }}
          collection_handle: ${{ secrets.SHOP_COLLECTION_HANDLE }}
  theme-check:
    name: Theme Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Shopify CLI
        run: npm install -g @shopify/cli @shopify/theme
      - name: Create theme-check config
        run: |
          echo 'extends: []' > .theme-check.yml
          echo 'ignore:' >> .theme-check.yml
          echo '  - node_modules/**' >> .theme-check.yml
      - name: Run Theme Check
        run: shopify theme check
